name: MCONE-Community
authors: [Marvin Hülsmann, Rufus Maiwald, Louis Bockel]
version: ${project.version}
main: eu.mcone.community.CommunityPlugin
depend: [MCONE-BukkitCoreSystem,MCONE-GameAPI]
softdepend: [NoCheatPlus]
permissions:
  community:
    description: Community Main Permission
    children:
      community.settings:
        description: change settings
      community.build:
        description: build on the community
